objects := main.o game.o
flags := -Wall -std=c++98
obj_flags := -c $(falgs)
SeaBattle: $(objects)
	g++ $(flags) $(objects) -o SeaBattle
main.o: main.cpp
	g++ $(obj_flag) main.cpp
game.o: game.cpp
	g++ $(obj_flags) game.cpp
clear:
	rm -f *.o *~
